# output file
artifacts_root: artifacts

data_ingestion:

  root_dir: artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:

  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:

  root_dir: artifacts/model_training
  data_path: artifacts/data_transformation/samsum_dataset
  model_name: google/pegasus-cnn_dailymail

model_evaluation:

  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts\model_training\pegasus-samsum-trained-model
  tokenizer_path: artifacts/model_training/tokenizer
  metric_full_name: artifacts/model_evaluation/metrics.csv
